name: Fetch Option Chain Data

on:
  schedule:
    - cron: '*/3 9-15 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # replace with your Python version
          
      - name: Install dependencies
        run: pip install mysql-connector-python pandas sqlalchemy requests pytz
      
      - name: Run script
        run: python mypythonscript.py
        env:
          DB_HOST: 89.117.188.204
          DB_NAME: u448360173_niftyoption
          DB_USER: u448360173_niftyoption
          DB_PASS: eDOzfAc8Y1

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

